### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by christiangleissner** [chesskit-app/chesskit-engine#6]
What are the expected nodes per second on a iPhone 14 Pro? With 6 cores I reach little more than 100k nodes/second. With 1 core around 30k nps. Is it possible to improve this?

After deactivating the Neural Network evaluation the nps improved significantly to around 800k nps at 6 cores. This opens up another question: Is the NN evaluation better regarding quality, so that a sacrifice in nps is justified?

I checked out the SmallFish app, unfortunately it does not show nps but it seems to be much faster in reaching a depth of 18-20. Of course given that this number is accurate.

**Comment by christiangleissner** [comment]
I would offer my help, but I have don't know anything about C++ and how to combine it with Swift. I really hope you can work it out, because your package is really nice and working with it is easy.

**Comment by pdil** [comment]
Performance has been improved in f4aafb615b34392a5b1fb32ed5a51dc40e92a9a0.
